project:
  type: website
  output-dir: docs

website:
  title: "training_workshops"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - nested.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

