project:
  type: website
  output-dir: docs

website:
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  index.qmd
          - text: Report a Bug
            url:  nested/nested.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

