project:
  type: website
  output-dir: docs

website:
  title: "Workshops"
  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - "---"
      - section: Presentations
        contents: presentations
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

