project:
  type: website
  output-dir: docs

website:
  navbar:
    menu:
      - index.qmd
      - nsted/nested.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

