project:
  type: website
  output-dir: docs

website:
  title: "Workshops"
  sidebar:
    contents: auto
    tools:
      - icon: github
        href: https://github.com/

format:
  html:
    theme: solor
    css: styles.css
    toc: true

editor: visual

