project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - section: "Presentations"
        contents:
          - presentations/good_data_practises.qmd
          - presentations/git_version_control.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

