project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - CV.qmd
      - section: "Workshops"
        contents:
          - presentations/good_data_practises.qmd
          - text: Data Wrangling
            url: presentations/data_wragling_of_field_data.qmd
          - presentations/git_version_control.qmd
      - section: "Presentations"
        contents:
          - presentations/good_data_practises.qmd
          - text: Data Wrangling
            url: presentations/data_wragling_of_field_data.qmd
          - presentations/git_version_control.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

