project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - about.qmd
      - index.qmd
      - /support_files/cv.qmd
      - section: "Workshops"
        contents:
          - text: Good data practises 
            url: presentations/good_data_practises.qmd
          - text: Data Wrangling
            url: presentations/data_wrangling_of_field_data.qmd
          - text: Introduction into Git
            url: presentations/git_version_control.qmd
          - text: Introduction into ggplot
            url: presentations/intro_into_ggplot.qmd
          - text: Reproducibility research
            url: presentations/reproducibility_workshop.qmd

      - section: "Presentaions"
        contents:
         - text: MCEVBD interview
         - url: presentations/MCEVBD_interview.qmd

  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
