project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - cv.qmd
      - section: "Workshops"
        contents:
          - text: Data Wrangling
          - url: presentations/good_data_practises.qmd
          - text: Data Wrangling
            url: presentations/data_wragling_of_field_data.qmd
          - text: Introduction into Git
            url: presentations/git_version_control.qmd
          - text: Introduction into ggplot
            url: presentations/intro_into_ggplot.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
