project:
  type: website
  output-dir: docs

website:
  title: "Workshops"
sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - about.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - nested/nested.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

